### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by shawninder**
Here's a first attempt. Basically sets `touch: true` if the device is detected as a phone or tablet... @youzi do you think this is sufficient for your needs?

### CODE REVIEW

**Comment by youzi** [comment]
@shawninder While this might be sufficient on the short term this is a solution that we can implement in our apps. For ua this isn't strict enough.

**Comment by shawninder** [comment]
@youzi Shall we merge and find a better solution after the release?

**Comment by jimdebeer** [comment]
just dont but this in ua -- its easy enough to do it by hand ua.device === 'phone' || ua.device === 'tablet' for now we use feature detection on the client

**Comment by shawninder** [comment]
@jimdebeer If we do put this in ua, then we can improve it without changing the code in the apps.. I think it would be a better idea to merge this here than to put that if everywhere in all our apps.

**Comment by jimdebeer** [comment]
no not in ua -- lets see later if we need this -- we use the more complete solution for now that is feature detection of touch (think of surface etc)

**Comment by jimdebeer** [comment]
('ontouchstart' in window) -- cant do this in ua ofcourse then it does not work in node

**Comment by shawninder** [comment]
For the surface computers, these have the word "touch" in their ua strings I believe, this is the kind of improvement I was talking about

**Comment by jimdebeer** [comment]
i think that is the whole point -- the half thing will not do anything -- merge as soon as it can replace the touchstart in window check

**Pull request closed without merging**
